#ifndef ANESTOR_CLOCK_RATES_H
#define ANESTOR_CLOCK_RATES_H

#define MASTER_CLOCK_SPEED_HZ (236250000 / 11.0)

#define CPU_CLOCK_SPEED_HZ (MASTER_CLOCK_SPEED_HZ / 12.0)
#define PPU_CLOCK_SPEED_HZ (MASTER_CLOCK_SPEED_HZ / 4.0)

#endif //ANESTOR_CLOCK_RATES_H
